name: sheets_i18n
description: A flutter tool to synchronize i18n (internationalization) arb files with google sheets.
version: 0.0.1
repository: https://github.com/lukas-h/sheets_i18n

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  gsheets: ^0.5.0
  intl_translation: ^0.20.0
  intl: ^0.19.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

executables:
  update: main