name: translation_service
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  gsheets: ^0.4.2
  intl_translation:
    git: https://github.com/scalabs/intl_translation
  intl: ^0.17.0

dev_dependencies:
  dartclub_lint: ^0.2.1
  test: ^1.6.0

executables:
  update: main